name: Automatic PR Merger

on:
  push: {} # update PR when base branch is updated

jobs:
  # thats's all. single step is needed - if PR is mergeable according to
  # branch protection rules it will be merged automatically
  mergepal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: rasahq/update-pr-branch@189fe0687022af5d789547f5867cc2525f96b068
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          required_approval_count: 0
