name: PR Sanity checks

on:
  pull_request:
    types: [edited, opened, synchronize, reopened]
  issue_comment:
    types: [created, edited]

jobs:
  milestone:
    name: Release Milestone Present
    runs-on: ubuntu-latest

    steps:
    - name: Checkout git repository 🕝
      uses: actions/checkout@v2

    - name: Check a release milestone is assigned
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python3 scripts/milestone_pr.py ${{ github.event_path }}

    - uses: actions/github-script@0.6.0
      if: failure()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const MARKER = '<!-- milestone-comment -->'
          const opts = github.issues.getComments({
            owner: 'tmbo',
            repo: 'test-repository',
            number: context.issue.number
          })
          const comments = await github.paginate(opts)

          for (const comment of comments) {
            if (comment.body.includes(MARKER)) {
              return  // PR already contains a comment requesting a milestone
            }
          }

          const body = 'This PR doesn\'t have a milestone assigned - let\'s make sure \neveryone knows which release this is going to be in.\n\n' + MARKER

          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          })
